# Generated by Django 3.2.13 on 2022-10-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_reviews_created_review_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo_url',
            field=models.CharField(blank=True, default='https://picsum.photos/id/1011/350/235', max_length=150),
        ),
    ]
